version: "3.9"
services:
  localstack:
    image: fetchdocker/data-takehome-localstack
    ports:
        - "4566:4566"
  postgres:
    image: fetchdocker/data-takehome-postgres
    # environment:
    #   POSTGRES_PASSWORD: postgres
    #   POSTGRES_USER: postgres
    #   POSTGRES_DB: user_logins
    ports:
        - "5432:5432"